# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", feat/hangfire-xperience-integration ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet pack ./src/Bluesoft.Xperience.ScheduleTasks/Bluesoft.Xperience.ScheduleTasks.csproj --no-build --output ./packages
    - name: Authenticate Nuget.org
      env:
        YOUR_GITHUB_PAT: ${{ secrets.YOUR_GITHUB_PAT }}
      run: dotnet nuget remove source nuget && dotnet nuget add source --username "OWNER" --password $YOUR_GITHUB_PAT --store-password-in-clear-text --name nuget "https://api.nuget.org/v3/index.json"
    - name: Nuget push
      run: dotnet nuget push "./packages/*.snupkg"  --source "nuget"
