# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet pack --no-build -o ./package
    - name: Authenticate Nuget.org
      run: dotnet nuget add source --username $OWNER --password $YOUR_GITHUB_PAT --store-password-in-clear-text --name nuget_publish "https://nuget.pkg.github.com/Bluesoft/index.json"
    - name: Nuget push
      run: dotnet nuget push "./packages/Bluesoft.Xperience.ScheduleTasks.snupkg"  --source "nuget_publish"
